### ISSUE TITLE
Search Generates InvalidConfig error

### ISSUE THREAD

**Issue by waynegraham** [minicomp/wax_tasks#43]
**Describe the bug**

When running the `rake wax:search qatar` task, `rake` exists with an error:

```
rake aborted!
WaxTasks::Error::InvalidConfig:
...
```

**To Reproduce**
1. Clone the repository
2. Run `bundle install`
3. Run `bundle exec rake wax:search qatar`

**Expected behavior**
The `/search/index.json` file to be generated.

**Error Trace  Output**
```
$bundle exec rake wax:search qatar --trace
rake aborted!
WaxTasks::Error::InvalidConfig:
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/wax_tasks-1.0.2/lib/wax_tasks/config.rb:54:in `search'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/wax_tasks-1.0.2/lib/wax_tasks/site.rb:40:in `generate_static_search'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/wax_tasks-1.0.2/lib/tasks/search.rake:12:in `block (3 levels) in <top (required)>'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/wax_tasks-1.0.2/lib/tasks/search.rake:12:in `each'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/wax_tasks-1.0.2/lib/tasks/search.rake:12:in `block (2 levels) in <top (required)>'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/<user>/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
/Users/<user>/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/<user>/.rvm/gems/ruby-2.6.3/bin/rake:23:in `load'
/Users/<user>/.rvm/gems/ruby-2.6.3/bin/rake:23:in `<main>'
/Users/<user>/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/<user>/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => wax:search
```

**Comment by waynegraham** [comment]
I didn't read the documentation properly...
